spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/reconciliation_db
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  batch:
    jdbc:
      initialize-schema: always